main1: hello1.asm hello1.obj
	C:\masm32\bin\ml /c /coff /Cp hello1.asm
	C:\masm32\bin\link -entry:main /subsystem:console hello1.obj
	hello1

main2: hello2.asm hello2.obj
	C:\masm32\bin\ml /c /coff /Cp hello2.asm
	C:\masm32\bin\link -entry:main /subsystem:console hello2.obj
	hello2

main3: hello3.asm hello3.obj
	C:\masm32\bin\ml /c /coff /Cp hello3.asm
	C:\masm32\bin\link -entry:main /subsystem:console hello3.obj
	hello3

main4: hello4.asm hello4.obj
	C:\masm32\bin\ml /c /coff /Cp hello4.asm
	C:\masm32\bin\link -entry:main /subsystem:console hello4.obj
	hello4

main5: hello5.asm hello5.obj
	C:\masm32\bin\ml /c /coff /Cp hello5.asm
	C:\masm32\bin\link -entry:main /subsystem:console hello5.obj
	hello5